name: 'ismene'
version: '1.0.0'
config-version: 2

profile: 'ismene'

model-paths: ["models"]
macro-paths: ["macros"]

seeds:
  ismene:
    employment_mapping_reference:
      +schema: Source
    geo_country_mapping:
      +schema: Source
    national_accounts_indicator:
      +schema: Source
    government_sectors:
      +schema: Source
    national_accounts_indicator_expenses:
      +schema: Source


models:
  ismene:
    Core:
      +schema: "Core"
    Staging:
      +schema: "Staging"
    Mart:
      +schema: "Mart"

