name: 'ismene'
version: '1.0.0'
config-version: 2

profile: 'ismene'

model-paths: ["models"]
macro-paths: ["macros"]

seeds:
  ismene:
    kpi_labels:
      +schema: Source  # Or whichever schema you'd like to place this in


models:
  ismene:
    Core:
      +schema: "Core"
    Staging:
      +schema: "Staging"
    Mart:
      +schema: "Mart"

