name: 'ismene'
version: '1.0.0'
config-version: 2

profile: 'ismene'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ismene:
    +schema: "{{ custom_schema_override() }}"
    staging:
      +schema: 'Staging'
    core:
      +schema: 'Core'
    mart:
      +schema: 'Mart'

packages:
  - package: dbt-labs/dbt_utils
    version: [">=0.8.0", "<0.9.0"]
