ismene:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: believer
      password: ~T;^n=:/>O\A64HGEYq,
      dbname: Antigone
      schema: "public" 
      port: 5432
      threads: 4
      keepalives_idle: 0
      search_path: 'Staging, Core, Mart'
