table neov_dim_geo
	lineageTag: 664e9490-04e5-4e70-8972-1d0351d4bcc0

	column geo
		dataType: string
		lineageTag: 64f4f3c6-1fff-4f24-814c-ea55da379b5b
		summarizeBy: none
		sourceColumn: geo

		annotation SummarizationSetBy = Automatic

	column pk_country
		dataType: int64
		formatString: 0
		lineageTag: e993bd07-7337-4dd3-a39a-c66d89a0a80a
		summarizeBy: none
		sourceColumn: pk_country

		annotation SummarizationSetBy = Automatic

	partition neov_dim_geo = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("127.0.0.1", "Antigone"),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Schema] = "Core")),
				    Core_dim_country = #"Filtered Rows"{[Schema="Core",Item="dim_country"]}[Data]
				in
				    Core_dim_country

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

