table neov_dim_date
	lineageTag: 2e332786-ebe2-4a0e-8c4e-f18e74f28c22

	measure neov_measures = DataTable("dummy", INTEGER ,{{1}})
		formatString: 0
		lineageTag: 2eae39fb-6c31-49bf-8d84-82fdc5f94df6

	column year_value
		dataType: int64
		formatString: 0
		lineageTag: 5449e198-d2c5-44af-8a17-1f27ba8db77f
		summarizeBy: none
		sourceColumn: year_value

		annotation SummarizationSetBy = Automatic

	partition neov_dim_date = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("127.0.0.1", "Antigone"),
				    eurostat_stag_date_table_dim = Source{[Schema="eurostat_stag",Item="date_table_dim"]}[Data]
				in
				    eurostat_stag_date_table_dim

	annotation PBI_ResultType = Table

