table neov_gov_fct_total
	lineageTag: ac718808-bab2-4b65-a924-9cbd7c9e05b7

	measure income_outcome_mio_eur = CALCULATE(SUM(neov_gov_fct_total[value]), neov_dim_unit[unit]= "MIO_EUR", neov_dim_date[year]= MAX(neov_dim_date[year]))
		lineageTag: 9511b920-0e39-488d-b339-e92f88c8f65b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure income_outcome_pc_gdp = CALCULATE(SUM(neov_gov_fct_total[value]), neov_dim_unit[unit]= "PC_GDP", neov_gov_fct_total[year] = MAX(neov_dim_date[year]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 095f62d5-2cde-4fd4-bca4-dc6cd0c15662

	measure int_pct =
			
			SWITCH (
			    SELECTEDVALUE ( neov_dim_unit[unit] ),
			    "MIO_EUR", [income_outcome_mio_eur],
			    "PC_GDP", [income_outcome_pc_gdp]
			)
		lineageTag: 508edf82-3fd0-4d36-8615-a5b8d0d5764e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure income_outcome_mio_eur_py = CALCULATE(SUM(neov_gov_fct_total[value]),  neov_dim_unit[unit]= "MIO_EUR", neov_dim_date[year]= MAX(neov_dim_date[year]) -1 )
		lineageTag: 29635643-95ec-472a-b558-9d676d55ae52

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'State with highest absolut expenditure' =
			
			MAXX(
			    TOPN(1,
			        SUMMARIZE(neov_dim_geo,neov_dim_geo[geo], "highest price", [int_pct]), [int_pct]),neov_dim_geo[geo])
		lineageTag: 1a7493f3-a815-4237-8f29-7e5540590126

	column value
		dataType: double
		lineageTag: 8df5ed24-198b-495b-8d5a-80d7c484c47f
		summarizeBy: sum
		sourceColumn: value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column fk_national_accounts
		dataType: int64
		formatString: 0
		lineageTag: 156f4a4d-1315-4ab4-9804-2837f73b7852
		summarizeBy: none
		sourceColumn: fk_national_accounts

		annotation SummarizationSetBy = Automatic

	column fk_country
		dataType: int64
		formatString: 0
		lineageTag: c01a5a4a-b360-44e6-b352-42ccd8f24cfc
		summarizeBy: none
		sourceColumn: fk_country

		annotation SummarizationSetBy = Automatic

	column fk_gov_sector
		dataType: int64
		formatString: 0
		lineageTag: 696bf5cc-0aca-46b5-a219-9cf12cac5314
		summarizeBy: sum
		sourceColumn: fk_gov_sector

		annotation SummarizationSetBy = Automatic

	column fk_unit
		dataType: int64
		formatString: 0
		lineageTag: 23d21f6d-36d2-44b4-a085-c4cf8fe89a0a
		summarizeBy: none
		sourceColumn: fk_unit

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		formatString: 0
		lineageTag: 39adde64-e9e0-4946-8341-c70720b22705
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	partition neov_gov_fct_total = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("127.0.0.1", "Antigone"),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Schema] = "Mart")),
				    Mart_fact_government_total = #"Filtered Rows"{[Schema="Mart",Item="fact_government_total"]}[Data]
				in
				    Mart_fact_government_total

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

