table neov_gov_geo_dim
	lineageTag: 664e9490-04e5-4e70-8972-1d0351d4bcc0

	column geo
		dataType: string
		lineageTag: 64f4f3c6-1fff-4f24-814c-ea55da379b5b
		summarizeBy: none
		sourceColumn: geo

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: 95c52df2-77ca-44d3-a782-088b38c4d890
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	partition neov_gov_geo_dim = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("127.0.0.1", "Antigone"),
				    eurostat_stag_DIM_EUROSTAT_GEO = Source{[Schema="eurostat_stag",Item="DIM_EUROSTAT_GEO"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(eurostat_stag_DIM_EUROSTAT_GEO,{"idt_geo"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

